# fly.toml app configuration file generated for smac-repo on 2025-11-19T09:14:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "smac-repo"
primary_region = "cdg"

[env]
  PORT = "5000"

[processes]
  app = "gunicorn main:app --bind 0.0.0.0:5000"


[http_service]
  internal_port = 5000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]
  concurrency = { type = "requests", soft_limit = 20, hard_limit = 25 }

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
  
